version: "3.8"

services: 
    postgres:
        container_name: postgres
        image: postgres:15
        ports: 
            - "5432:5432"
        environment:
            - POSTGRES_DB=MyDB
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=yourStrongPassword12#
        volumes: 
            - pgdata:/var/lib/postgresql/data
    web-app:
        container_name: web-app
        build:
            dockerfile: ./TaskBoard.WebApp/Dockerfile
        ports: 
            - "5000:80"
        restart: on-failure

volumes:
    pgdata: